DEFAULT_PAGE_SIZE = 6
MAX_PAGE_SIZE = 20
PAGE_SIZE_QUERY_PARAM = "limit"

MIN_AMOUNT = 1
MIN_COOKING_TIME = 1

BASE62_ALPHABET = (
    "0123456789abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
)

FRONT_RECIPE_PATH = "/recipes/{id}"
