[tool.black]
line-length = 79
skip_string_normalization = true
target-version = ['py38']
include = '\.py$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | __pycache__
  | build
  | dist
)/
'''