TAG_NAME_MAX_LEN = 64
TAG_SLUG_MAX_LEN = 32

INGREDIENT_NAME_MAX_LEN = 128
INGREDIENT_UNIT_MAX_LEN = 64

RECIPE_NAME_MAX_LEN = 256
COOKING_TIME_MIN = 1
SERVINGS_MIN = 1
SERVINGS_MAX = 50

SHORTLINK_CODE_MAX_LEN = 16
