services:
  db:
    image: postgres:13-alpine
    container_name: foodgram-db
    environment:
      POSTGRES_DB: ${DB_NAME:-foodgram}
      POSTGRES_USER: ${POSTGRES_USER:-foodgram}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-foodgram}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  # Одноразовый сборщик фронта
  frontend:
    image: node:20-alpine
    container_name: foodgram-frontend-build
    working_dir: /app
    volumes:
      - ../frontend:/app
      - ../frontend/build:/app/build
    command: sh -c "npm ci && npm run build"
    restart: "no"

  backend:
    container_name: foodgram-back
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      STATIC_ROOT: /app/static
      MEDIA_ROOT: /app/media
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    expose:
      - "8000"
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 foodgram.wsgi
      "

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/static:ro
      - media_data:/media:ro
      - ../frontend/build:/usr/share/nginx/html:ro

volumes:
  pg_data:
  static_data:
  media_data:
