version: "3.9"

networks:
  foodgram_network:
    driver: bridge

volumes:
  db_data:
  static_volume:
  media_volume:
  front_build:

services:
  db:
    image: postgres:13-alpine
    platform: linux/arm64
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    networks:
      - foodgram_network
    container_name: foodgram_db

  backend:
    image: pyryanova/foodgram_backend
    platform: linux/amd64
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - foodgram_network
    container_name: foodgram_backend

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app:ro
      - front_build:/dist
    command: >
      sh -c "npm ci && npm run build && mkdir -p /dist && cp -r /app/build/* /dist"
    networks:
      - foodgram_network
    container_name: foodgram_frontend
    restart: "no"

  gateway:
    image: pyryanova/foodgram_gateway
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - front_build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/var/html/static
      - media_volume:/var/html/media
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network
    container_name: foodgram_gateway
    restart: always
