networks:
  foodgram_network:
    driver: bridge

volumes:
  db_data:
  static_volume:
  media_volume:
  frontend_volume:

services:
  db:
    image: postgres:13-alpine
    platform: linux/arm64
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    networks:
      - foodgram_network
    container_name: foodgram_db

  backend:
    image: pyryanova/foodgram_backend
    platform: linux/amd64
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - foodgram_network
    container_name: foodgram_backend

  frontend:
    image: pyryanova/foodgram_frontend
    platform: linux/amd64
    volumes:
      - frontend_volume:/usr/share/nginx/html
    command: >
      sh -lc "cp -r /opt/build/. /usr/share/nginx/html && tail -f /dev/null"
    networks:
      - foodgram_network
    container_name: foodgram_frontend
    restart: "no"

  gateway:
    image: pyryanova/foodgram_gateway
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - static_volume:/app/static
      - media_volume:/app/media
      - frontend_volume:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network
    container_name: foodgram_gateway
    restart: always
