# Generated by Django 4.2.14 on 2025-09-09 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=1, help_text='На сколько порций рассчитан рецепт.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество порций'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Название'),
        ),
    ]
