# Generated by Django 4.2.14 on 2025-09-10 12:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_favorite_recipe_alter_shoppingcart_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='servings',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Сколько порций планируете купить; если пусто — как в рецепте.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порций для покупки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
