name: Foodgram CI/CD
on: [push]

jobs:
  build_and_push_backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest

  build_and_push_frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    needs: build_and_push_backend
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest

  deploy:
    name: SSH deploy
    runs-on: ubuntu-latest
    needs: build_and_push_frontend
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script_stop: true
          script: |
            set -euo pipefail
            cd /home/${{ secrets.USER }}/foodgram
            sudo chown -R $USER:$USER /home/${{ secrets.USER }}/foodgram || true
            git config --global --add safe.directory /home/${{ secrets.USER }}/foodgram || true
            if [ -d .git ]; then
              git fetch --all
              git reset --hard origin/main
              git clean -fd
            fi
            sudo sed -i 's/\r$//' /Users/pyryanova/Dev/foodgram/docker-compose.production.yml || true
            sudo docker-compose -f /Users/pyryanova/Dev/foodgram/docker-compose.production.yml pull
            sudo docker-compose -f /Users/pyryanova/Dev/foodgram/docker-compose.production.yml up -d
            sudo docker-compose -f /Users/pyryanova/Dev/foodgram/docker-compose.production.yml exec -T backend python manage.py migrate --noinput
            sudo docker-compose -f /Users/pyryanova/Dev/foodgram/docker-compose.production.yml exec -T backend python manage.py collectstatic --noinput
            sudo docker-compose -f /Users/pyryanova/Dev/foodgram/docker-compose.production.yml exec -T backend python manage.py load_ingredients || true

  notify:
    name: Telegram Notify
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Foodgram: деплой успешно выполнен"
